# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c72e998d3b5d804d7c841f832850e5be48579b27f4a5d98f4787ad19e0a42670413e583e308c270dfd92f266c75d2c6fd99539bcea67d85e610c3956965d603

test:
  secret_key_base: c5680e36ddeb62e547068bb8c36e2b91643526f533af948431fe8505c46c8e3955de0c905164bd6a7ba678bf7472fcdb809d6223490aeddfdd4a9ad92b46a356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
